root: true
extends:
  - "plugin:@ubiservices-eslint/genericLibrary"
  - "prettier"
plugins:
  - "prettier"
rules:
  "prettier/prettier": ["error"]
  "@typescript-eslint/no-var-requires": "off"
  "@typescript-eslint/naming-convention":
    - "error"
    - selector: "objectLiteralProperty"
      format: null

  "@typescript-eslint/ban-types":
    - "error"
    - types:
        Object: false
        object: false
        Function: false
      extendDefaults: true

  "@typescript-eslint/consistent-indexed-object-style":
    - "error"
    - "index-signature"

  # TODO: enable following rules and fix the code.
  "@typescript-eslint/ban-ts-comment": "off"
  "@typescript-eslint/no-extraneous-class": "off"
  "@typescript-eslint/restrict-plus-operands": "off"
  "node/no-process-env": "off"
  no-new-func: "off"
